# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vishal Subramanian
email: vishalsubbu97@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Website of Vishal Subramanian
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vishal-subbu.github.io" # the base hostname & protocol for your site
github_username:  vishal-subbu
facebook_username: vishal.subramanian.1

# Build settings
markdown: kramdown